/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CourseVideo = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'videoFile' : ExternalBlob,
});
export const Question = IDL.Record({
  'correctOption' : IDL.Nat,
  'difficulty' : IDL.Opt(IDL.Text),
  'explanation' : IDL.Text,
  'questionText' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Course = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'description' : IDL.Text,
  'videos' : IDL.Vec(CourseVideo),
});
export const MockTest = IDL.Record({
  'id' : IDL.Text,
  'creator' : IDL.Principal,
  'subject' : IDL.Text,
  'questions' : IDL.Vec(Question),
  'price' : IDL.Nat,
});
export const Syllabus = IDL.Record({
  'subject' : IDL.Text,
  'topics' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'signupTimestamp' : IDL.Opt(IDL.Int),
  'gmail' : IDL.Opt(IDL.Text),
  'mobile' : IDL.Opt(IDL.Text),
  'photo' : ExternalBlob,
  'profileComplete' : IDL.Bool,
});
export const SessionState = IDL.Record({
  'role' : UserRole,
  'isAuthenticated' : IDL.Bool,
  'profile' : IDL.Opt(UserProfile),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const TestResult = IDL.Record({
  'user' : IDL.Principal,
  'attempts' : IDL.Nat,
  'score' : IDL.Nat,
  'testId' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCourse' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(CourseVideo)],
      [],
      [],
    ),
  'addMockTest' : IDL.Func([IDL.Text, IDL.Vec(Question), IDL.Nat], [], []),
  'addShoppingItem' : IDL.Func([ShoppingItem], [], []),
  'addSyllabus' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteCourse' : IDL.Func([IDL.Text], [], []),
  'deleteMockTest' : IDL.Func([IDL.Text], [], []),
  'deleteShoppingItem' : IDL.Func([IDL.Text], [], []),
  'deleteSyllabus' : IDL.Func([IDL.Text], [], []),
  'generateOtp' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getAllMockTests' : IDL.Func([], [IDL.Vec(MockTest)], ['query']),
  'getAllSyllabi' : IDL.Func([], [IDL.Vec(Syllabus)], ['query']),
  'getAllUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactInfo' : IDL.Func(
      [],
      [IDL.Record({ 'email' : IDL.Text, 'phone' : IDL.Text })],
      ['query'],
    ),
  'getCourse' : IDL.Func([IDL.Text], [Course], ['query']),
  'getCoursesBySubject' : IDL.Func([IDL.Text], [IDL.Vec(Course)], ['query']),
  'getMockTest' : IDL.Func([IDL.Text], [MockTest], ['query']),
  'getMockTestPrice' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getMockTestsBySubject' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MockTest)],
      ['query'],
    ),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
  'getSessionState' : IDL.Func([], [SessionState], ['query']),
  'getShoppingItems' : IDL.Func([], [IDL.Vec(ShoppingItem)], ['query']),
  'getSitemap' : IDL.Func([], [IDL.Text], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getSyllabus' : IDL.Func([IDL.Text], [Syllabus], ['query']),
  'getTestResults' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(TestResult)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'getUserProgress' : IDL.Func(
      [IDL.Principal],
      [IDL.Record({ 'totalTests' : IDL.Nat, 'averageScore' : IDL.Nat })],
      ['query'],
    ),
  'getUserPurchases' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'recordPurchase' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitTestResult' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCourse' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(CourseVideo)],
      [],
      [],
    ),
  'updateMockTest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(Question), IDL.Nat],
      [],
      [],
    ),
  'updateMockTestPrice' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateProfile' : IDL.Func(
      [IDL.Text, ExternalBlob, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateProfilePicture' : IDL.Func([ExternalBlob], [], []),
  'updateShoppingItem' : IDL.Func([IDL.Text, ShoppingItem], [], []),
  'updateSyllabus' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'verifyOtp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CourseVideo = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'videoFile' : ExternalBlob,
  });
  const Question = IDL.Record({
    'correctOption' : IDL.Nat,
    'difficulty' : IDL.Opt(IDL.Text),
    'explanation' : IDL.Text,
    'questionText' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Course = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'description' : IDL.Text,
    'videos' : IDL.Vec(CourseVideo),
  });
  const MockTest = IDL.Record({
    'id' : IDL.Text,
    'creator' : IDL.Principal,
    'subject' : IDL.Text,
    'questions' : IDL.Vec(Question),
    'price' : IDL.Nat,
  });
  const Syllabus = IDL.Record({
    'subject' : IDL.Text,
    'topics' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'signupTimestamp' : IDL.Opt(IDL.Int),
    'gmail' : IDL.Opt(IDL.Text),
    'mobile' : IDL.Opt(IDL.Text),
    'photo' : ExternalBlob,
    'profileComplete' : IDL.Bool,
  });
  const SessionState = IDL.Record({
    'role' : UserRole,
    'isAuthenticated' : IDL.Bool,
    'profile' : IDL.Opt(UserProfile),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const TestResult = IDL.Record({
    'user' : IDL.Principal,
    'attempts' : IDL.Nat,
    'score' : IDL.Nat,
    'testId' : IDL.Text,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCourse' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(CourseVideo)],
        [],
        [],
      ),
    'addMockTest' : IDL.Func([IDL.Text, IDL.Vec(Question), IDL.Nat], [], []),
    'addShoppingItem' : IDL.Func([ShoppingItem], [], []),
    'addSyllabus' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteCourse' : IDL.Func([IDL.Text], [], []),
    'deleteMockTest' : IDL.Func([IDL.Text], [], []),
    'deleteShoppingItem' : IDL.Func([IDL.Text], [], []),
    'deleteSyllabus' : IDL.Func([IDL.Text], [], []),
    'generateOtp' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getAllMockTests' : IDL.Func([], [IDL.Vec(MockTest)], ['query']),
    'getAllSyllabi' : IDL.Func([], [IDL.Vec(Syllabus)], ['query']),
    'getAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactInfo' : IDL.Func(
        [],
        [IDL.Record({ 'email' : IDL.Text, 'phone' : IDL.Text })],
        ['query'],
      ),
    'getCourse' : IDL.Func([IDL.Text], [Course], ['query']),
    'getCoursesBySubject' : IDL.Func([IDL.Text], [IDL.Vec(Course)], ['query']),
    'getMockTest' : IDL.Func([IDL.Text], [MockTest], ['query']),
    'getMockTestPrice' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getMockTestsBySubject' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MockTest)],
        ['query'],
      ),
    'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
    'getSessionState' : IDL.Func([], [SessionState], ['query']),
    'getShoppingItems' : IDL.Func([], [IDL.Vec(ShoppingItem)], ['query']),
    'getSitemap' : IDL.Func([], [IDL.Text], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getSyllabus' : IDL.Func([IDL.Text], [Syllabus], ['query']),
    'getTestResults' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(TestResult)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'getUserProgress' : IDL.Func(
        [IDL.Principal],
        [IDL.Record({ 'totalTests' : IDL.Nat, 'averageScore' : IDL.Nat })],
        ['query'],
      ),
    'getUserPurchases' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'recordPurchase' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitTestResult' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCourse' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(CourseVideo)],
        [],
        [],
      ),
    'updateMockTest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(Question), IDL.Nat],
        [],
        [],
      ),
    'updateMockTestPrice' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateProfile' : IDL.Func(
        [IDL.Text, ExternalBlob, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateProfilePicture' : IDL.Func([ExternalBlob], [], []),
    'updateShoppingItem' : IDL.Func([IDL.Text, ShoppingItem], [], []),
    'updateSyllabus' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'verifyOtp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };