/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Course {
  'id' : string,
  'title' : string,
  'subject' : string,
  'description' : string,
  'videos' : Array<CourseVideo>,
}
export interface CourseVideo {
  'id' : string,
  'title' : string,
  'duration' : bigint,
  'videoFile' : ExternalBlob,
}
export type ExternalBlob = Uint8Array;
export interface MockTest {
  'id' : string,
  'creator' : Principal,
  'subject' : string,
  'questions' : Array<Question>,
  'price' : bigint,
}
export interface Question {
  'correctOption' : bigint,
  'difficulty' : [] | [string],
  'explanation' : string,
  'questionText' : string,
  'options' : Array<string>,
}
export interface SessionState {
  'role' : UserRole,
  'isAuthenticated' : boolean,
  'profile' : [] | [UserProfile],
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface Syllabus { 'subject' : string, 'topics' : Array<string> }
export interface TestResult {
  'user' : Principal,
  'attempts' : bigint,
  'score' : bigint,
  'testId' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'signupTimestamp' : [] | [bigint],
  'gmail' : [] | [string],
  'mobile' : [] | [string],
  'photo' : ExternalBlob,
  'profileComplete' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCourse' : ActorMethod<
    [string, string, string, Array<CourseVideo>],
    undefined
  >,
  'addMockTest' : ActorMethod<[string, Array<Question>, bigint], undefined>,
  'addShoppingItem' : ActorMethod<[ShoppingItem], undefined>,
  'addSyllabus' : ActorMethod<[string, Array<string>], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteCourse' : ActorMethod<[string], undefined>,
  'deleteMockTest' : ActorMethod<[string], undefined>,
  'deleteShoppingItem' : ActorMethod<[string], undefined>,
  'deleteSyllabus' : ActorMethod<[string], undefined>,
  'generateOtp' : ActorMethod<[string], string>,
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getAllMockTests' : ActorMethod<[], Array<MockTest>>,
  'getAllSyllabi' : ActorMethod<[], Array<Syllabus>>,
  'getAllUserProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getAllUsers' : ActorMethod<[], Array<Principal>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactInfo' : ActorMethod<[], { 'email' : string, 'phone' : string }>,
  'getCourse' : ActorMethod<[string], Course>,
  'getCoursesBySubject' : ActorMethod<[string], Array<Course>>,
  'getMockTest' : ActorMethod<[string], MockTest>,
  'getMockTestPrice' : ActorMethod<[string], bigint>,
  'getMockTestsBySubject' : ActorMethod<[string], Array<MockTest>>,
  'getProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getSessionState' : ActorMethod<[], SessionState>,
  'getShoppingItems' : ActorMethod<[], Array<ShoppingItem>>,
  'getSitemap' : ActorMethod<[], string>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getSyllabus' : ActorMethod<[string], Syllabus>,
  'getTestResults' : ActorMethod<[Principal], Array<TestResult>>,
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  'getUserProgress' : ActorMethod<
    [Principal],
    { 'totalTests' : bigint, 'averageScore' : bigint }
  >,
  'getUserPurchases' : ActorMethod<[Principal], Array<string>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'recordPurchase' : ActorMethod<[Principal, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitTestResult' : ActorMethod<[string, bigint, bigint], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCourse' : ActorMethod<
    [string, string, string, string, Array<CourseVideo>],
    undefined
  >,
  'updateMockTest' : ActorMethod<
    [string, string, Array<Question>, bigint],
    undefined
  >,
  'updateMockTestPrice' : ActorMethod<[string, bigint], undefined>,
  'updateProfile' : ActorMethod<
    [string, ExternalBlob, [] | [string], [] | [string]],
    undefined
  >,
  'updateProfilePicture' : ActorMethod<[ExternalBlob], undefined>,
  'updateShoppingItem' : ActorMethod<[string, ShoppingItem], undefined>,
  'updateSyllabus' : ActorMethod<[string, Array<string>], undefined>,
  'verifyOtp' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];