/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SessionState {
    role: UserRole;
    isAuthenticated: boolean;
    profile?: UserProfile;
}
export interface MockTest {
    id: string;
    creator: Principal;
    subject: string;
    questions: Array<Question>;
    price: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface CourseVideo {
    id: string;
    title: string;
    duration: bigint;
    videoFile: ExternalBlob;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface TestResult {
    user: Principal;
    attempts: bigint;
    score: bigint;
    testId: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Course {
    id: string;
    title: string;
    subject: string;
    description: string;
    videos: Array<CourseVideo>;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface Question {
    correctOption: bigint;
    difficulty?: string;
    explanation: string;
    questionText: string;
    options: Array<string>;
}
export interface Syllabus {
    subject: string;
    topics: Array<string>;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
    signupTimestamp?: bigint;
    gmail?: string;
    mobile?: string;
    photo: ExternalBlob;
    profileComplete: boolean;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCourse(title: string, description: string, subject: string, videos: Array<CourseVideo>): Promise<void>;
    addMockTest(subject: string, questions: Array<Question>, price: bigint): Promise<void>;
    addShoppingItem(item: ShoppingItem): Promise<void>;
    addSyllabus(subject: string, topics: Array<string>): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    deleteCourse(courseId: string): Promise<void>;
    deleteMockTest(testId: string): Promise<void>;
    deleteShoppingItem(productName: string): Promise<void>;
    deleteSyllabus(subject: string): Promise<void>;
    generateOtp(mobile: string): Promise<string>;
    getAllCourses(): Promise<Array<Course>>;
    getAllMockTests(): Promise<Array<MockTest>>;
    getAllSyllabi(): Promise<Array<Syllabus>>;
    getAllUserProfiles(): Promise<Array<[Principal, UserProfile]>>;
    getAllUsers(): Promise<Array<Principal>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContactInfo(): Promise<{
        email: string;
        phone: string;
    }>;
    getCourse(courseId: string): Promise<Course>;
    getCoursesBySubject(subject: string): Promise<Array<Course>>;
    getMockTest(testId: string): Promise<MockTest>;
    getMockTestPrice(testId: string): Promise<bigint>;
    getMockTestsBySubject(subject: string): Promise<Array<MockTest>>;
    getProfile(beneficiary: Principal): Promise<UserProfile | null>;
    getSessionState(): Promise<SessionState>;
    getShoppingItems(): Promise<Array<ShoppingItem>>;
    getSitemap(): Promise<string>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getSyllabus(subject: string): Promise<Syllabus>;
    getTestResults(user: Principal): Promise<Array<TestResult>>;
    getUserProfile(user: Principal): Promise<UserProfile>;
    getUserProgress(user: Principal): Promise<{
        totalTests: bigint;
        averageScore: bigint;
    }>;
    getUserPurchases(user: Principal): Promise<Array<string>>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    recordPurchase(user: Principal, itemId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    submitTestResult(testId: string, score: bigint, attempts: bigint): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateCourse(courseId: string, title: string, description: string, subject: string, videos: Array<CourseVideo>): Promise<void>;
    updateMockTest(testId: string, subject: string, questions: Array<Question>, price: bigint): Promise<void>;
    updateMockTestPrice(testId: string, newPrice: bigint): Promise<void>;
    updateProfile(name: string, photo: ExternalBlob, mobile: string | null, gmail: string | null): Promise<void>;
    updateProfilePicture(photo: ExternalBlob): Promise<void>;
    updateShoppingItem(productName: string, item: ShoppingItem): Promise<void>;
    updateSyllabus(subject: string, topics: Array<string>): Promise<void>;
    verifyOtp(mobile: string, otp: string): Promise<boolean>;
}
import type { Course as _Course, CourseVideo as _CourseVideo, ExternalBlob as _ExternalBlob, MockTest as _MockTest, Question as _Question, SessionState as _SessionState, StripeSessionStatus as _StripeSessionStatus, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCourse(arg0: string, arg1: string, arg2: string, arg3: Array<CourseVideo>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCourse(arg0, arg1, arg2, await to_candid_vec_n8(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCourse(arg0, arg1, arg2, await to_candid_vec_n8(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async addMockTest(arg0: string, arg1: Array<Question>, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMockTest(arg0, to_candid_vec_n12(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMockTest(arg0, to_candid_vec_n12(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async addShoppingItem(arg0: ShoppingItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addShoppingItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addShoppingItem(arg0);
            return result;
        }
    }
    async addSyllabus(arg0: string, arg1: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSyllabus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSyllabus(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteCourse(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCourse(arg0);
            return result;
        }
    }
    async deleteMockTest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMockTest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMockTest(arg0);
            return result;
        }
    }
    async deleteShoppingItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteShoppingItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteShoppingItem(arg0);
            return result;
        }
    }
    async deleteSyllabus(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSyllabus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSyllabus(arg0);
            return result;
        }
    }
    async generateOtp(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateOtp(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateOtp(arg0);
            return result;
        }
    }
    async getAllCourses(): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCourses();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCourses();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMockTests(): Promise<Array<MockTest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMockTests();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMockTests();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSyllabi(): Promise<Array<Syllabus>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSyllabi();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSyllabi();
            return result;
        }
    }
    async getAllUserProfiles(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactInfo(): Promise<{
        email: string;
        phone: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactInfo();
            return result;
        }
    }
    async getCourse(arg0: string): Promise<Course> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourse(arg0);
                return from_candid_Course_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourse(arg0);
            return from_candid_Course_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoursesBySubject(arg0: string): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoursesBySubject(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoursesBySubject(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMockTest(arg0: string): Promise<MockTest> {
        if (this.processError) {
            try {
                const result = await this.actor.getMockTest(arg0);
                return from_candid_MockTest_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMockTest(arg0);
            return from_candid_MockTest_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMockTestPrice(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMockTestPrice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMockTestPrice(arg0);
            return result;
        }
    }
    async getMockTestsBySubject(arg0: string): Promise<Array<MockTest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMockTestsBySubject(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMockTestsBySubject(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSessionState(): Promise<SessionState> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionState();
                return from_candid_SessionState_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionState();
            return from_candid_SessionState_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShoppingItems(): Promise<Array<ShoppingItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShoppingItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShoppingItems();
            return result;
        }
    }
    async getSitemap(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getSitemap();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSitemap();
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSyllabus(arg0: string): Promise<Syllabus> {
        if (this.processError) {
            try {
                const result = await this.actor.getSyllabus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSyllabus(arg0);
            return result;
        }
    }
    async getTestResults(arg0: Principal): Promise<Array<TestResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestResults(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestResults(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_UserProfile_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_UserProfile_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProgress(arg0: Principal): Promise<{
        totalTests: bigint;
        averageScore: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProgress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProgress(arg0);
            return result;
        }
    }
    async getUserPurchases(arg0: Principal): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPurchases(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPurchases(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async recordPurchase(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPurchase(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPurchase(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n44(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n44(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async submitTestResult(arg0: string, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTestResult(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTestResult(arg0, arg1, arg2);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateCourse(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<CourseVideo>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCourse(arg0, arg1, arg2, arg3, await to_candid_vec_n8(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCourse(arg0, arg1, arg2, arg3, await to_candid_vec_n8(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async updateMockTest(arg0: string, arg1: string, arg2: Array<Question>, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMockTest(arg0, arg1, to_candid_vec_n12(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMockTest(arg0, arg1, to_candid_vec_n12(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async updateMockTestPrice(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMockTestPrice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMockTestPrice(arg0, arg1);
            return result;
        }
    }
    async updateProfile(arg0: string, arg1: ExternalBlob, arg2: string | null, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, await to_candid_ExternalBlob_n11(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n46(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n46(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, await to_candid_ExternalBlob_n11(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n46(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n46(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateProfilePicture(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfilePicture(await to_candid_ExternalBlob_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfilePicture(await to_candid_ExternalBlob_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateShoppingItem(arg0: string, arg1: ShoppingItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateShoppingItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateShoppingItem(arg0, arg1);
            return result;
        }
    }
    async updateSyllabus(arg0: string, arg1: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSyllabus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSyllabus(arg0, arg1);
            return result;
        }
    }
    async verifyOtp(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyOtp(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyOtp(arg0, arg1);
            return result;
        }
    }
}
async function from_candid_CourseVideo_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CourseVideo): Promise<CourseVideo> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_Course_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Course): Promise<Course> {
    return await from_candid_record_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_MockTest_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MockTest): MockTest {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Question_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Question): Question {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
async function from_candid_SessionState_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionState): Promise<SessionState> {
    return await from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    subject: string;
    description: string;
    videos: Array<_CourseVideo>;
}): Promise<{
    id: string;
    title: string;
    subject: string;
    description: string;
    videos: Array<CourseVideo>;
}> {
    return {
        id: value.id,
        title: value.title,
        subject: value.subject,
        description: value.description,
        videos: await from_candid_vec_n20(_uploadFile, _downloadFile, value.videos)
    };
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    duration: bigint;
    videoFile: _ExternalBlob;
}): Promise<{
    id: string;
    title: string;
    duration: bigint;
    videoFile: ExternalBlob;
}> {
    return {
        id: value.id,
        title: value.title,
        duration: value.duration,
        videoFile: await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value.videoFile)
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    creator: Principal;
    subject: string;
    questions: Array<_Question>;
    price: bigint;
}): {
    id: string;
    creator: Principal;
    subject: string;
    questions: Array<Question>;
    price: bigint;
} {
    return {
        id: value.id,
        creator: value.creator,
        subject: value.subject,
        questions: from_candid_vec_n27(_uploadFile, _downloadFile, value.questions),
        price: value.price
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    correctOption: bigint;
    difficulty: [] | [string];
    explanation: string;
    questionText: string;
    options: Array<string>;
}): {
    correctOption: bigint;
    difficulty?: string;
    explanation: string;
    questionText: string;
    options: Array<string>;
} {
    return {
        correctOption: value.correctOption,
        difficulty: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.difficulty)),
        explanation: value.explanation,
        questionText: value.questionText,
        options: value.options
    };
}
async function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    signupTimestamp: [] | [bigint];
    gmail: [] | [string];
    mobile: [] | [string];
    photo: _ExternalBlob;
    profileComplete: boolean;
}): Promise<{
    name: string;
    signupTimestamp?: bigint;
    gmail?: string;
    mobile?: string;
    photo: ExternalBlob;
    profileComplete: boolean;
}> {
    return {
        name: value.name,
        signupTimestamp: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.signupTimestamp)),
        gmail: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.gmail)),
        mobile: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.mobile)),
        photo: await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value.photo),
        profileComplete: value.profileComplete
    };
}
async function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    role: _UserRole;
    isAuthenticated: boolean;
    profile: [] | [_UserProfile];
}): Promise<{
    role: UserRole;
    isAuthenticated: boolean;
    profile?: UserProfile;
}> {
    return {
        role: from_candid_UserRole_n37(_uploadFile, _downloadFile, value.role),
        isAuthenticated: value.isAuthenticated,
        profile: record_opt_to_undefined(await from_candid_opt_n36(_uploadFile, _downloadFile, value.profile))
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_tuple_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserProfile]): Promise<[Principal, UserProfile]> {
    return [
        value[0],
        await from_candid_UserProfile_n33(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n43(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
async function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Course>): Promise<Array<Course>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Course_n18(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CourseVideo>): Promise<Array<CourseVideo>> {
    return await Promise.all(value.map(async (x)=>await from_candid_CourseVideo_n21(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MockTest>): Array<MockTest> {
    return value.map((x)=>from_candid_MockTest_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Question>): Array<Question> {
    return value.map((x)=>from_candid_Question_n28(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserProfile]>): Promise<Array<[Principal, UserProfile]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n32(_uploadFile, _downloadFile, x)));
}
async function to_candid_CourseVideo_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CourseVideo): Promise<_CourseVideo> {
    return await to_candid_record_n10(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Question_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Question): _Question {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n45(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    duration: bigint;
    videoFile: ExternalBlob;
}): Promise<{
    id: string;
    title: string;
    duration: bigint;
    videoFile: _ExternalBlob;
}> {
    return {
        id: value.id,
        title: value.title,
        duration: value.duration,
        videoFile: await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.videoFile)
    };
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    correctOption: bigint;
    difficulty?: string;
    explanation: string;
    questionText: string;
    options: Array<string>;
}): {
    correctOption: bigint;
    difficulty: [] | [string];
    explanation: string;
    questionText: string;
    options: Array<string>;
} {
    return {
        correctOption: value.correctOption,
        difficulty: value.difficulty ? candid_some(value.difficulty) : candid_none(),
        explanation: value.explanation,
        questionText: value.questionText,
        options: value.options
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    signupTimestamp?: bigint;
    gmail?: string;
    mobile?: string;
    photo: ExternalBlob;
    profileComplete: boolean;
}): Promise<{
    name: string;
    signupTimestamp: [] | [bigint];
    gmail: [] | [string];
    mobile: [] | [string];
    photo: _ExternalBlob;
    profileComplete: boolean;
}> {
    return {
        name: value.name,
        signupTimestamp: value.signupTimestamp ? candid_some(value.signupTimestamp) : candid_none(),
        gmail: value.gmail ? candid_some(value.gmail) : candid_none(),
        mobile: value.mobile ? candid_some(value.mobile) : candid_none(),
        photo: await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.photo),
        profileComplete: value.profileComplete
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Question>): Array<_Question> {
    return value.map((x)=>to_candid_Question_n13(_uploadFile, _downloadFile, x));
}
async function to_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CourseVideo>): Promise<Array<_CourseVideo>> {
    return await Promise.all(value.map(async (x)=>await to_candid_CourseVideo_n9(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
